# Required for puppeteer to work
dist: trusty
sudo: required

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

language: node_js
node_js:
- node
- '12'
- '10'

# https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
matrix:
  fast_finish: true

script: npm test -- --coverage --verbose
