# Required for puppeteer to work
dist: trusty
sudo: required

language: node_js
node_js:
- node
- '10'
- '8'

# https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
matrix:
  fast_finish: true

script: npm test -- --coverage --verbose
